import { getReceiptData } from "@/server/repositories/receipts";
import { renderReceiptPdf } from "@/server/pdf/receipt-pdf";
import { canHandleMoney } from "@/server/auth";
import { handleError, json } from "@/server/http";

/**
 * The printable payment receipt, rendered on demand.
 *
 * Gated on `canHandleMoney` (secretary + admin), matching who may see the
 * payments list this is printed from — a receipt names a patient and states what
 * they paid. A dietitian never collects money and so never prints one.
 *
 * No IDOR surface: the id addresses a Payment, and the whole receipt is derived
 * from that payment's own settlement. There is no client-supplied scope to widen.
 *
 * `?disposition=attachment` saves instead of displaying; the default is inline so
 * the Print button opens the browser's own PDF viewer, which owns the print
 * dialog — the same convention the Food List PDF uses.
 *
 * Nothing here reads Settings: every figure comes from the frozen payment rows,
 * so a reprint years later reproduces the original amounts exactly.
 */
export async function GET(req: Request, { params }: { params: Promise<{ paymentId: string }> }) {
  try {
    if (!(await canHandleMoney(req))) return json({ error: "Not allowed" }, 403);
    const { paymentId } = await params;
    const data = await getReceiptData(paymentId);
    const pdf = await renderReceiptPdf(data);

    const attach = new URL(req.url).searchParams.get("disposition") === "attachment";
    // The receipt number is generated by the server (`RCP-YYYY-NNNNNN`), so it is
    // already safe in a header; the RFC 5987 form is belt-and-braces.
    const filename = `Receipt-${data.receiptNumber}.pdf`;
    return new Response(new Uint8Array(pdf), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Length": String(pdf.length),
        "Content-Disposition": `${attach ? "attachment" : "inline"}; filename="${filename}"; filename*=UTF-8''${encodeURIComponent(filename)}`,
        // A receipt is derived from immutable rows, but it names a patient —
        // never let a shared cache hold it.
        "Cache-Control": "private, no-store",
      },
    });
  } catch (e) {
    return handleError(e);
  }
}
